[2022-11-29T05:21:44.949+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: Can_I_change_name_to_this.task_5 manual__2022-11-29T05:21:04.079211+00:00 [queued]>
[2022-11-29T05:21:44.990+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: Can_I_change_name_to_this.task_5 manual__2022-11-29T05:21:04.079211+00:00 [queued]>
[2022-11-29T05:21:44.992+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-29T05:21:44.994+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-11-29T05:21:44.995+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-29T05:21:45.046+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): task_5> on 2022-11-29 05:21:04.079211+00:00
[2022-11-29T05:21:45.075+0000] {standard_task_runner.py:55} INFO - Started process 149 to run task
[2022-11-29T05:21:45.094+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Can_I_change_name_to_this', 'task_5', 'manual__2022-11-29T05:21:04.079211+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/dags.py', '--cfg-path', '/tmp/tmpxzl9wp2y']
[2022-11-29T05:21:45.098+0000] {standard_task_runner.py:83} INFO - Job 21: Subtask task_5
[2022-11-29T05:21:45.755+0000] {task_command.py:376} INFO - Running <TaskInstance: Can_I_change_name_to_this.task_5 manual__2022-11-29T05:21:04.079211+00:00 [running]> on host 68e922a5ec23
[2022-11-29T05:21:46.256+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Can_I_change_name_to_this
AIRFLOW_CTX_TASK_ID=task_5
AIRFLOW_CTX_EXECUTION_DATE=2022-11-29T05:21:04.079211+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-29T05:21:04.079211+00:00
[2022-11-29T05:21:46.276+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-11-29T05:21:46.285+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/tasks/put_to_s3.py ']
[2022-11-29T05:21:46.416+0000] {subprocess.py:86} INFO - Output:
[2022-11-29T05:21:48.705+0000] {subprocess.py:93} INFO - 2022-11-29 05:21:48,702 | __main__ |put_to_s3.py | INFO | now putting raw file to s3
[2022-11-29T05:21:59.156+0000] {subprocess.py:93} INFO - 2022-11-29 05:21:59,154 | __main__ |put_to_s3.py | INFO | successfully put raw file to s3
[2022-11-29T05:21:59.162+0000] {subprocess.py:93} INFO - 2022-11-29 05:21:59,157 | __main__ |put_to_s3.py | INFO | put raw file to s3 have used -10.451426130000073s
[2022-11-29T05:21:59.266+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2022-11-29T05:21:59.330+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=Can_I_change_name_to_this, task_id=task_5, execution_date=20221129T052104, start_date=20221129T052144, end_date=20221129T052159
[2022-11-29T05:21:59.411+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2022-11-29T05:21:59.458+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
