[2022-11-29T06:43:03.338+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: Can_I_change_name_to_this.task_5 manual__2022-11-29T06:42:13.205094+00:00 [queued]>
[2022-11-29T06:43:03.387+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: Can_I_change_name_to_this.task_5 manual__2022-11-29T06:42:13.205094+00:00 [queued]>
[2022-11-29T06:43:03.391+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-29T06:43:03.399+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-11-29T06:43:03.405+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-29T06:43:03.441+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): task_5> on 2022-11-29 06:42:13.205094+00:00
[2022-11-29T06:43:03.505+0000] {standard_task_runner.py:55} INFO - Started process 2625 to run task
[2022-11-29T06:43:03.549+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Can_I_change_name_to_this', 'task_5', 'manual__2022-11-29T06:42:13.205094+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/dags.py', '--cfg-path', '/tmp/tmp5tr8puvy']
[2022-11-29T06:43:03.570+0000] {standard_task_runner.py:83} INFO - Job 43: Subtask task_5
[2022-11-29T06:43:03.960+0000] {task_command.py:376} INFO - Running <TaskInstance: Can_I_change_name_to_this.task_5 manual__2022-11-29T06:42:13.205094+00:00 [running]> on host 68e922a5ec23
[2022-11-29T06:43:04.271+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Can_I_change_name_to_this
AIRFLOW_CTX_TASK_ID=task_5
AIRFLOW_CTX_EXECUTION_DATE=2022-11-29T06:42:13.205094+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-29T06:42:13.205094+00:00
[2022-11-29T06:43:04.285+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-11-29T06:43:04.313+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/tasks/put_to_s3.py ']
[2022-11-29T06:43:04.555+0000] {subprocess.py:86} INFO - Output:
[2022-11-29T06:43:08.454+0000] {subprocess.py:93} INFO - {"message": "now putting raw file to s3", "time": "2022-11-29T06:43:08.437741"}
[2022-11-29T06:43:14.802+0000] {subprocess.py:93} INFO - {"message": "successfully put raw file to s3", "time": "2022-11-29T06:43:14.788360"}
[2022-11-29T06:43:14.818+0000] {subprocess.py:93} INFO - {"message": "put raw file to s3 have used -6.349572711000292s", "time": "2022-11-29T06:43:14.796826"}
[2022-11-29T06:43:14.989+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2022-11-29T06:43:15.213+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=Can_I_change_name_to_this, task_id=task_5, execution_date=20221129T064213, start_date=20221129T064303, end_date=20221129T064315
[2022-11-29T06:43:15.321+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2022-11-29T06:43:15.372+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
