[2022-12-17T09:54:02.466+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: Can_I_change_name_to_this.task_11 manual__2022-12-17T09:53:31.433840+00:00 [queued]>
[2022-12-17T09:54:02.643+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: Can_I_change_name_to_this.task_11 manual__2022-12-17T09:53:31.433840+00:00 [queued]>
[2022-12-17T09:54:02.659+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-17T09:54:02.681+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2022-12-17T09:54:02.685+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-17T09:54:02.847+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): task_11> on 2022-12-17 09:53:31.433840+00:00
[2022-12-17T09:54:02.884+0000] {standard_task_runner.py:55} INFO - Started process 1766 to run task
[2022-12-17T09:54:02.945+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Can_I_change_name_to_this', 'task_11', 'manual__2022-12-17T09:53:31.433840+00:00', '--job-id', '108', '--raw', '--subdir', 'DAGS_FOLDER/dags.py', '--cfg-path', '/tmp/tmpe0mbip1n']
[2022-12-17T09:54:02.953+0000] {standard_task_runner.py:83} INFO - Job 108: Subtask task_11
[2022-12-17T09:54:03.433+0000] {task_command.py:389} INFO - Running <TaskInstance: Can_I_change_name_to_this.task_11 manual__2022-12-17T09:53:31.433840+00:00 [running]> on host 502390ac5559
[2022-12-17T09:54:04.416+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Can_I_change_name_to_this
AIRFLOW_CTX_TASK_ID=task_11
AIRFLOW_CTX_EXECUTION_DATE=2022-12-17T09:53:31.433840+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-17T09:53:31.433840+00:00
[2022-12-17T09:54:04.789+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-12-17T09:54:04.816+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/tasks/redshift/basic_load_to_redshift.py']
[2022-12-17T09:54:05.106+0000] {subprocess.py:86} INFO - Output:
[2022-12-17T09:54:06.247+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2022-12-17T09:54:06.262+0000] {subprocess.py:93} INFO -   File "/opt/***/tasks/redshift/basic_load_to_redshift.py", line 10, in <module>
[2022-12-17T09:54:06.266+0000] {subprocess.py:93} INFO -     from logger.Logger import Log
[2022-12-17T09:54:06.268+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'logger'
[2022-12-17T09:54:06.284+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2022-12-17T09:54:06.376+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-12-17T09:54:06.481+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=Can_I_change_name_to_this, task_id=task_11, execution_date=20221217T095331, start_date=20221217T095402, end_date=20221217T095406
[2022-12-17T09:54:06.627+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 108 for task task_11 (Bash command failed. The command returned a non-zero exit code 1.; 1766)
[2022-12-17T09:54:06.832+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-12-17T09:54:06.919+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
