[2022-11-29T07:48:57.838+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: Can_I_change_name_to_this.task_5 manual__2022-11-29T07:47:51.849269+00:00 [queued]>
[2022-11-29T07:48:57.925+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: Can_I_change_name_to_this.task_5 manual__2022-11-29T07:47:51.849269+00:00 [queued]>
[2022-11-29T07:48:57.933+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-29T07:48:57.939+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-11-29T07:48:57.943+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-29T07:48:58.135+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): task_5> on 2022-11-29 07:47:51.849269+00:00
[2022-11-29T07:48:58.199+0000] {standard_task_runner.py:55} INFO - Started process 235 to run task
[2022-11-29T07:48:58.269+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Can_I_change_name_to_this', 'task_5', 'manual__2022-11-29T07:47:51.849269+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/dags.py', '--cfg-path', '/tmp/tmp2jman_5a']
[2022-11-29T07:48:58.274+0000] {standard_task_runner.py:83} INFO - Job 50: Subtask task_5
[2022-11-29T07:48:58.779+0000] {task_command.py:376} INFO - Running <TaskInstance: Can_I_change_name_to_this.task_5 manual__2022-11-29T07:47:51.849269+00:00 [running]> on host 68e922a5ec23
[2022-11-29T07:48:59.349+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Can_I_change_name_to_this
AIRFLOW_CTX_TASK_ID=task_5
AIRFLOW_CTX_EXECUTION_DATE=2022-11-29T07:47:51.849269+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-29T07:47:51.849269+00:00
[2022-11-29T07:48:59.387+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-11-29T07:48:59.405+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/tasks/put_to_s3.py ']
[2022-11-29T07:48:59.456+0000] {subprocess.py:86} INFO - Output:
[2022-11-29T07:49:11.424+0000] {subprocess.py:93} INFO - {"message": "now putting raw file to s3", "time": "2022-11-29T07:49:11.402187"}
[2022-11-29T07:49:19.714+0000] {subprocess.py:93} INFO - {"message": "successfully put raw file to s3", "time": "2022-11-29T07:49:19.712164"}
[2022-11-29T07:49:19.753+0000] {subprocess.py:93} INFO - {"message": "put raw file to s3 have used -8.303829545999179s", "time": "2022-11-29T07:49:19.752456"}
[2022-11-29T07:49:20.803+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2022-11-29T07:49:21.228+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=Can_I_change_name_to_this, task_id=task_5, execution_date=20221129T074751, start_date=20221129T074857, end_date=20221129T074921
[2022-11-29T07:49:21.739+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2022-11-29T07:49:23.972+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
