[2022-11-29T06:20:04.288+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: Can_I_change_name_to_this.task_5 manual__2022-11-29T06:19:39.257639+00:00 [queued]>
[2022-11-29T06:20:04.344+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: Can_I_change_name_to_this.task_5 manual__2022-11-29T06:19:39.257639+00:00 [queued]>
[2022-11-29T06:20:04.349+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-29T06:20:04.351+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-11-29T06:20:04.355+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-29T06:20:04.405+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): task_5> on 2022-11-29 06:19:39.257639+00:00
[2022-11-29T06:20:04.446+0000] {standard_task_runner.py:55} INFO - Started process 1462 to run task
[2022-11-29T06:20:04.456+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Can_I_change_name_to_this', 'task_5', 'manual__2022-11-29T06:19:39.257639+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/dags.py', '--cfg-path', '/tmp/tmprd_1bhyi']
[2022-11-29T06:20:04.463+0000] {standard_task_runner.py:83} INFO - Job 37: Subtask task_5
[2022-11-29T06:20:04.808+0000] {task_command.py:376} INFO - Running <TaskInstance: Can_I_change_name_to_this.task_5 manual__2022-11-29T06:19:39.257639+00:00 [running]> on host 68e922a5ec23
[2022-11-29T06:20:05.258+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Can_I_change_name_to_this
AIRFLOW_CTX_TASK_ID=task_5
AIRFLOW_CTX_EXECUTION_DATE=2022-11-29T06:19:39.257639+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-29T06:19:39.257639+00:00
[2022-11-29T06:20:05.278+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-11-29T06:20:05.287+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/tasks/put_to_s3.py ']
[2022-11-29T06:20:05.354+0000] {subprocess.py:86} INFO - Output:
[2022-11-29T06:20:07.647+0000] {subprocess.py:93} INFO - {"message": "now putting raw file to s3", "time": "2022-11-29T06:20:07.629192"}
[2022-11-29T06:20:20.268+0000] {subprocess.py:93} INFO - {"message": "successfully put raw file to s3", "time": "2022-11-29T06:20:20.257861"}
[2022-11-29T06:20:20.274+0000] {subprocess.py:93} INFO - {"message": "put raw file to s3 have used -12.629065212999194s", "time": "2022-11-29T06:20:20.270961"}
[2022-11-29T06:20:20.446+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2022-11-29T06:20:20.555+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=Can_I_change_name_to_this, task_id=task_5, execution_date=20221129T061939, start_date=20221129T062004, end_date=20221129T062020
[2022-11-29T06:20:20.657+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2022-11-29T06:20:20.695+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
