[2022-11-29T05:21:48.713+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: Can_I_change_name_to_this.task_7 manual__2022-11-29T05:21:04.079211+00:00 [queued]>
[2022-11-29T05:21:48.790+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: Can_I_change_name_to_this.task_7 manual__2022-11-29T05:21:04.079211+00:00 [queued]>
[2022-11-29T05:21:48.794+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-29T05:21:48.797+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-11-29T05:21:48.799+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-29T05:21:48.825+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): task_7> on 2022-11-29 05:21:04.079211+00:00
[2022-11-29T05:21:48.833+0000] {standard_task_runner.py:55} INFO - Started process 163 to run task
[2022-11-29T05:21:48.838+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Can_I_change_name_to_this', 'task_7', 'manual__2022-11-29T05:21:04.079211+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/dags.py', '--cfg-path', '/tmp/tmpte9oknvs']
[2022-11-29T05:21:48.841+0000] {standard_task_runner.py:83} INFO - Job 22: Subtask task_7
[2022-11-29T05:21:48.906+0000] {task_command.py:376} INFO - Running <TaskInstance: Can_I_change_name_to_this.task_7 manual__2022-11-29T05:21:04.079211+00:00 [running]> on host 68e922a5ec23
[2022-11-29T05:21:48.980+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Can_I_change_name_to_this
AIRFLOW_CTX_TASK_ID=task_7
AIRFLOW_CTX_EXECUTION_DATE=2022-11-29T05:21:04.079211+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-29T05:21:04.079211+00:00
[2022-11-29T05:21:48.992+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-11-29T05:21:48.995+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/tasks/data_cleansing_counter_stat.py']
[2022-11-29T05:21:49.006+0000] {subprocess.py:86} INFO - Output:
[2022-11-29T05:21:49.379+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2022-11-29T05:21:49.381+0000] {subprocess.py:93} INFO -   File "/opt/***/tasks/data_cleansing_counter_stat.py", line 3, in <module>
[2022-11-29T05:21:49.382+0000] {subprocess.py:93} INFO -     from pyspark.sql.types import *
[2022-11-29T05:21:49.384+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'pyspark'
[2022-11-29T05:21:49.404+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2022-11-29T05:21:49.418+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-11-29T05:21:49.426+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=Can_I_change_name_to_this, task_id=task_7, execution_date=20221129T052104, start_date=20221129T052148, end_date=20221129T052149
[2022-11-29T05:21:49.438+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 22 for task task_7 (Bash command failed. The command returned a non-zero exit code 1.; 163)
[2022-11-29T05:21:49.466+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-11-29T05:21:49.487+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
