[2022-12-17T09:54:06.917+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: Can_I_change_name_to_this.task_12 manual__2022-12-17T09:53:31.433840+00:00 [queued]>
[2022-12-17T09:54:06.976+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: Can_I_change_name_to_this.task_12 manual__2022-12-17T09:53:31.433840+00:00 [queued]>
[2022-12-17T09:54:06.986+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-17T09:54:06.988+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2022-12-17T09:54:06.989+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-17T09:54:07.061+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): task_12> on 2022-12-17 09:53:31.433840+00:00
[2022-12-17T09:54:07.071+0000] {standard_task_runner.py:55} INFO - Started process 1770 to run task
[2022-12-17T09:54:07.080+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Can_I_change_name_to_this', 'task_12', 'manual__2022-12-17T09:53:31.433840+00:00', '--job-id', '109', '--raw', '--subdir', 'DAGS_FOLDER/dags.py', '--cfg-path', '/tmp/tmp98agjli3']
[2022-12-17T09:54:07.084+0000] {standard_task_runner.py:83} INFO - Job 109: Subtask task_12
[2022-12-17T09:54:07.497+0000] {task_command.py:389} INFO - Running <TaskInstance: Can_I_change_name_to_this.task_12 manual__2022-12-17T09:53:31.433840+00:00 [running]> on host 502390ac5559
[2022-12-17T09:54:09.729+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Can_I_change_name_to_this
AIRFLOW_CTX_TASK_ID=task_12
AIRFLOW_CTX_EXECUTION_DATE=2022-12-17T09:53:31.433840+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-17T09:53:31.433840+00:00
[2022-12-17T09:54:09.787+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-12-17T09:54:09.801+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/tasks/redshift/basic_load_to_redshift.py']
[2022-12-17T09:54:09.883+0000] {subprocess.py:86} INFO - Output:
[2022-12-17T09:54:10.523+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2022-12-17T09:54:10.545+0000] {subprocess.py:93} INFO -   File "/opt/***/tasks/redshift/basic_load_to_redshift.py", line 10, in <module>
[2022-12-17T09:54:10.546+0000] {subprocess.py:93} INFO -     from logger.Logger import Log
[2022-12-17T09:54:10.553+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'logger'
[2022-12-17T09:54:10.567+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2022-12-17T09:54:10.744+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-12-17T09:54:10.855+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=Can_I_change_name_to_this, task_id=task_12, execution_date=20221217T095331, start_date=20221217T095406, end_date=20221217T095410
[2022-12-17T09:54:10.980+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 109 for task task_12 (Bash command failed. The command returned a non-zero exit code 1.; 1770)
[2022-12-17T09:54:11.185+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-12-17T09:54:11.356+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
